name: Maestro E2E Tests Android (Local Build)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.1'
        cache: 'yarn'

    - name: Install dependencies
      run: |
        yarn install

    - name: Install Maestro
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        export PATH="$PATH:$HOME/.maestro/bin"
        echo "$HOME/.maestro/bin" >> $GITHUB_PATH

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Manual Emulator Setup
      run: |
        # Install platform tools and emulator
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;default;x86_64"
        
        # Create AVD
        echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-30;default;x86_64" -d "pixel_4" -f
        
        # Start emulator
        $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &
        
        # Wait for boot
        $ANDROID_HOME/platform-tools/adb wait-for-device
        while ! $ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed | grep -q "1"; do
          sleep 5
        done
        echo "Emulator ready"

    - name: Build Android APK with Safe Environment
      run: |
        # Set safe environment variables that won't crash the app
        export POSTHOG_KEY=""
        export SENTRY_DSN=""
        export SENTRY_AUTH_TOKEN=""
        export API_MODE="mock"
        export API_URL="https://jsonplaceholder.typicode.com"
        export EAS_PROJECT_ID=""
        
        # Build the APK
        npx expo prebuild --platform android
        cd android && SENTRY_DISABLE_AUTO_UPLOAD=true ./gradlew assembleRelease -Psentry.disable=true

    - name: Install APK
      run: |
        adb wait-for-device
        adb install android/app/build/outputs/apk/release/app-release.apk
        echo "APK installed successfully"

    - name: Wait for app to be ready
      run: |
        # Wait for emulator to be fully ready
        adb shell sleep 10

    - name: Run Maestro Tests
      run: |
        maestro test .maestro/ --format junit --output results.xml
      env:
        MAESTRO_APP_ID: com.zeeshantechdots.myapp

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: |
          results.xml
          .maestro/**/*.png

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maestro Test Results
        path: results.xml
        reporter: java-junit

    - name: Upload APK for debugging
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: built-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 1