name: Maestro E2E Tests Android (Local Build)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.1'
        cache: 'yarn'

    - name: Install dependencies
      run: |
        yarn install

    - name: Install Maestro
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        export PATH="$PATH:$HOME/.maestro/bin"
        echo "$HOME/.maestro/bin" >> $GITHUB_PATH

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Android APK with Safe Environment
      run: |
        # Set safe environment variables that won't crash the app
        export POSTHOG_KEY=""
        export SENTRY_DSN=""
        export SENTRY_AUTH_TOKEN=""
        export API_MODE="mock"
        export API_URL="https://jsonplaceholder.typicode.com"
        export EAS_PROJECT_ID=""
        
        # Build the APK
        npx expo prebuild --platform android
        cd android && ./gradlew assembleRelease -Dsentry.skip=true

    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        arch: x86_64
        profile: pixel_4
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
        disable-animations: false

    - name: Install APK
      run: |
        adb wait-for-device
        adb install android/app/build/outputs/apk/release/app-release.apk
        echo "APK installed successfully"

    - name: Wait for app to be ready
      run: |
        # Wait for emulator to be fully ready
        adb shell sleep 10

    - name: Run Maestro Tests
      run: |
        maestro test .maestro/ --format junit --output results.xml
      env:
        MAESTRO_APP_ID: com.zeeshantechdots.myapp

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: |
          results.xml
          .maestro/**/*.png

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maestro Test Results
        path: results.xml
        reporter: java-junit

    - name: Upload APK for debugging
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: built-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 1